# Site settings
name: PM2 Documentation
email: contact@pm2.io
description: 'PM2 - Guide, References, Tutorials and Best Practices about PM2 and Node.js.'

# Build settings
sass:
  style: compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge

repository: 'keymetrics/doc-pm2'
permalink: pretty
plugins:
  - jekyll-redirect-from

destination: docs

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - misc
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - yarn.lock
